# Generated by Django 4.2.4 on 2023-11-03 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone_pinterest', '0003_board_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='home.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
