# Generated by Django 4.2.4 on 2023-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_pinterest', '0006_alter_pin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
