# Generated by Django 4.2.4 on 2023-11-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone_pinterest', '0010_alter_board_private_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
