# Generated by Django 4.2.4 on 2023-11-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_pinterest', '0012_board_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='board',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='board'),
        ),
        migrations.AddField(
            model_name='board',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='board'),
        ),
    ]
